version: '3'
services:
  app_server:
    build: .
    image: node-express-dev:1.0
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:3000"
    command: node server.js
    
